# Generated by Django 2.1.5 on 2019-01-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('joined_job', models.DateField(blank=True)),
                ('birth_date', models.DateField(blank=True)),
                ('salary', models.FloatField(blank=True)),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='grid.Job')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['-full_name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.SET, to='grid.Status'),
        ),
    ]
